### ISSUE TITLE
Salus Orb

### ISSUE THREAD

**Issue by jborrey** [coinbase/salus#39]
From #10, @raphdev brought up the following:

>A small improvement we've made is simplifying for CircleCI through an [orb](https://circleci.com/orbs/). This allows teams to integrate Salus and any configuration, simply by including the orb. The orb would have the correct docker image/version, and remote configuration locations managed by the security team. One benefit of this is that we no longer require updating several pipelines for updates that aren't in the container itself, such as handling of reporting, since these are reused from the orb.
Does something like this sound like a valuable contribution?

Thanks for bringing this to my attention! I need to keep up with the CircleCI blog more.

Yeah I certainly think that a Salus orb could be useful. Not sure if the Coinbase team wants to own the creation of that or @raphdev, are you considering making your orb general purpose to work outside of your org?

**Comment by raphdev** [comment]
My intention is to make the orb general purpose. Since production CircleCI orbs are public, it makes sense to make our Salus orb useful outside our org. We'd be more than happy to contribute this :)

**Comment by jborrey** [comment]
Sounds great! Thank you.

Orb source code seems public so if other orgs want to have their own version or modify it that should be easy for them to do.

**Comment by jsulinski** [comment]
Is this orb publicly available? Not seeing it in the registry at https://circleci.com/orbs/registry/

Thanks!

**Comment by nishils** [comment]
As far as I know, not yet. If you know how to build an orb, we could use help on that front. @raphdev are you still able to make the Salus orb public?

**Comment by jsulinski** [comment]
Never have before, but gave it a shot. It's currently published as a development version.

federacy/salus@dev:0.0.1

https://github.com/federacy/salus-orb

**Comment by raphdev** [comment]
We've been running a dev version in my org, but it's not public just yet. I can work on a prod release this week since I'm continuing Salus-related work for the next few weeks. 

@jsulinski Nice job! I like how you parameterized some of the Salus local config options. The orb I have doesn't expose these options, only command line flags.

Given there are two orbs in development, do we want to coordinate efforts? If so, how do we proceed?

**Comment by jborrey** [comment]
Yeah nice job @jsulinski - and I appreciate the fact that you kept the default params quite strong (the README mislead me, but in the `orb.yml` is see it's different).

@raphdev I see pros and cons for both options. If we have two implementations and they are significantly different (not sure how different orbs can be ...) then it's probably worth having both. If you think they will be very similar, I'd lean towards collaboration provided that @jsulinski is happy to facilitate code reviews/merging.

**Comment by jsulinski** [comment]
Thanks! I'm happy to facilitate code reviews/merging. Will update the docs with the defaults and other examples soon, just wanted to make sure I'm on the right path.

**Comment by jsulinski** [comment]
@raphdev We should collaborate as I doubt there will be significant disparity in functionality and it's MIT licensed by nature of being an Orb. 

By the way, I think even dev Orbs are public, just not published to the visible registry. I tested using the one at federacy/salus@dev:0.0.1 from a different org and it was accessible.

**Comment by jsulinski** [comment]
@raphdev Any update here? I've added some additional documentation and am otherwise ready to publish the orb.

**Comment by raphdev** [comment]
@jsulinski You are right, dev orbs are also world-readable. I was under the impression you needed to be in the org. 

Feel free to try `wework/salus@dev:salus-testing`. Since the code for the orb is still private, you can process a config to resolve the orb:

```config.yml
version: 2.1
orbs:
  salus: wework/salus@dev:salus-testing
workflows:
  security_scan:
    jobs:
      - salus/scan
```

Then run `circleci config process config.yml > expanded_config.yml` and you should see the `salus/scan` job resolved in `expanded_config.yml`. You can test running it locally by copying to a repo and running `circleci build --job salus/scan -c expanded_config.yml`.

The orb is similar in many ways, some noteworthy differences:

* I didn't paremeterize the config options. Instead we expose `config` that maps to the `--config` command line option, and use the local/remote configurations to control it. This may be valuable to control multiple repos using the orb:
```
salus/scan:
    - config: "http://myconfig.internal/salus.yml"
```
* This orb maintains CircleCI default directories (e.g., `/home/repo`) for its working directory. I don't think this matters too much, unless we want compatibility with Circle convenience images for any reason. I found it convenient for overriding the least path settings. You can change this through a `source_dir` option.
* The job executor is configurable. I thought this was important for testing custom Salus builds, and I expect people may want to be able to define and pass their own images to run Salus without needing a new orb:
```
version: 2.1
orbs:
  salus: wework/salus@dev:salus-testing
executors:
  salus_latest:
    docker:
      - image: coinbase/salus:latest
workflows:
  security_scan:
    jobs:
      - salus/scan
          salus_container:
            name: salus_latest
```
This also works with [private images](https://circleci.com/docs/2.0/private-images/).

I think the configuration options are worthwhile to consolidate to support a variety of scenarios. Likewise, the executor is helpful for custom, experimental, or otherwise company specific Salus scanners. Thoughts?

**Comment by jsulinski** [comment]
Awesome, thanks! I agree with you and I'll work on merging them.

**Comment by jsresearch** [comment]
@raphdev I tested and merged in the executor change. 

I also implemented your other suggestions, let me know if you agree with the approach: https://github.com/federacy/salus-orb/tree/raph-suggestions

Some challenges I ran into: 

- There are relative paths in the report_node_modules and report_python_modules, ie: https://github.com/coinbase/salus/blob/master/lib/salus/scanners/report_node_modules.rb#L47 which required setting the working_directory parameter.
- --config is nested below --repo-path, so I couldn't use full paths
- You can override --configuration with an environment variable, but then it is rather ambiguous to the user which is being used. Worked around this with some shell logic, which clearly tells the user if the configuration file they specified is not present. The environment variable can still be used to utilize a configuration file over HTTPS.

**Comment by jsulinski** [comment]
@raphdev I tested and merged in the executor change. 

I also implemented your other suggestions, let me know if you agree with the approach: https://github.com/federacy/salus-orb/tree/raph-suggestions

Some challenges I ran into: 

- There are relative paths in report_node_modules and report_python_modules, ie: https://github.com/coinbase/salus/blob/master/lib/salus/scanners/report_node_modules.rb#L47 which required setting the `working_directory` parameter.
- --config is nested below --repo-path, so I couldn't use full paths
- You can override --configuration with an environment variable, but then it is rather ambiguous to the user which is being used. Worked around this with some shell logic, which clearly tells the user if the configuration file they specified is not present. The environment variable can still be used to utilize a configuration file over HTTPS. 

If you agree with the approach, I'll go ahead and publish a non-dev version of the Orb.

**Comment by raphdev** [comment]
Awesome! I went ahead and PR'd the changes so I could comment there.

> There are relative paths in report_node_modules and report_python_modules, ie: https://github.com/coinbase/salus/blob/master/lib/salus/scanners/report_node_modules.rb#L47 which required setting the working_directory parameter.

I confirmed this breaks for me too. Does your comment about `--config` and `--repo-path` affect these utils as well, preventing us from using full paths for those?

I agree with the approach - the workarounds are well thought out.

**Comment by jsulinski** [comment]
Correct, in addition to `report_uri`. For example: 

https://github.com/coinbase/salus/blob/master/lib/salus/processor.rb#L92-L94
https://github.com/coinbase/salus/blob/master/lib/salus/processor.rb#L39

I fixed a few typos and pegged the tag to 2.4.2. Also tested a handful of different configurations. I'll merge the PR and Publish tomorrow unless you have any objections!

**Comment by jsulinski** [comment]
The reason for the relative paths is to put any generated configuration and the default report outside of the repo directory so that we don't taint it.

**Comment by jsulinski** [comment]
Orb has been published. Thanks so much for the help @raphdev!

https://circleci.com/orbs/registry/orb/federacy/salus

**Comment by jsulinski** [comment]
Added a usage example here: https://github.com/coinbase/salus/pull/54

**Comment by jborrey** [comment]
Awesome work y'all. Thanks again for helping grow this project.
